### ISSUE TITLE
bad effect on RealEstate10k

### ISSUE THREAD

**Issue by yuyu0927** [facebookresearch/PoseDiffusion#16]
Hi,

I ran the demo.py (without GGS) on a serie of images [(youtube link)](https://www.youtube.com/watch?v=TFYdFphVyZw) coming from test dataset of RealEstate10k. Here is the result of the visualisation, which is not very good. I am not sure if I've done something wrong about visualisation code. Can you help me with this? Thanks in advance.
![Weixin Image_20231010173357](https://github.com/facebookresearch/PoseDiffusion/assets/34515369/cb9f60b3-f6ef-47a8-8bc7-7f7cf703fdb0)

**Comment by jytime** [comment]
Hi,

There is no prior knowledge for this, but this is the hypothesis based on my "observations" in various samples. My feeling is, the model will tend to think some frames are quite close like a "group"/"cluster", probably due to their quite similar appearance.  In some bad cases there are two, three or more groups. I am trying to analyse this in our future work.

I think 720p should be good. Usually it is best to extract the frames from videos by the original resolution.

**Comment by yuyu0927** [comment]
Hi,

I really appreciate your help. I’ve learnt a lot. Your assumption about “group”/“cluster” sounds very interesting and attractive. Look forward to your future work.

kind regards,
Qingyu

**Comment by yuyu0927** [comment]
Hi Jianyuan,

I fed the same data with high resolution to the model with GGS, but the results are very similar in both cases. It seems that GGS optimization is kind of limited for this type of data (RealEstate10k). I am not very sure, maybe I need to test more data. By the way, very much looking forward to CKPT for Re10K. Thanks!

Below are result without GGS and result with GGS, respectively.
![image](https://github.com/facebookresearch/PoseDiffusion/assets/34515369/15407a2b-5cdd-4034-82c5-8c62f369c7a1)
![image](https://github.com/facebookresearch/PoseDiffusion/assets/34515369/47e9f32a-d1f3-4b72-81b7-3c3a2991f726)

Kind regards,
Qingyu

**Comment by jytime** [comment]
Hi Qingyu,

Thanks for your feedback. I will keep this issue open until I release the Re10K ckpt.

**Comment by jytime** [comment]
Hey @yuyu0927 , it may be too late (sorry for the delay), I just uploaded a checkpoint for re10k
