### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by zhuhu00** [facebookresearch/PoseDiffusion#21]
Hi,  Jianyuan,
I tried to retrain in co3dv2, but there was an “out of memory” error in only one or two categories. Is there any way to solve it? my device is RTX 3090 with 24GB memory.

![image](https://github.com/facebookresearch/PoseDiffusion/assets/29742046/9275774a-008a-421e-883b-5d6b233a3fbf)

**Comment by jytime** [comment]
Hi, you can make the value of ```max_images``` smaller. Sorry I should make it clearer. ```max_images``` actually takes the role of batch size in our code, because we use a dynamic batch size. In the code below, you can see ```n_seqs = self.max_images // n_per_seq```. https://github.com/facebookresearch/PoseDiffusion/blob/8ce281338d46561f8a82b6f3a7675ad1712fc12f/pose_diffusion/util/train_util.py#L27-L59
