### ISSUE TITLE
Relative camera pose estimation on ScanNet

### ISSUE THREAD

**Issue by ACuOoOoO** [facebookresearch/PoseDiffusion#24]
It is an interesting work for absolute camera pose estimation. I wonder whether it can be used for relative pose estimation, which is crucial for visual localization task. So, I tried it for two-view pose estimation on SuperGlue's test split of ScanNet (https://github.com/magicleap/SuperGluePretrainedNetwork/blob/master/assets/scannet_test_pairs_with_gt.txt).  To this end, I have transformed pytorch3D coordinate into colmap, and computed relative poses from absolute poses. However, it does not work.  
Is it possible to apply PoseDiffusion to relative pose camera estimation in the real world? Or, is there any other important detail I have ignored?

**Comment by jytime** [comment]
Hi,

Thanks for your interest. In our own preliminary experiments, PoseDiffusion can indeed deal with two-view relative camera pose estimation. However, the currently available checkpoint was trained for scenarios with 3 to N frames. To optimize performance for two-view scenarios, you may need to re-train with 2 to N frames. This is possibly important because, despite PoseDiffusion's ability to generalize across different frame counts, the jump from 3 to 2 frames involves specific challenges, which theoretically belongs to multi-view geometry or epipolar geometry.

Another important consideration is the role of GGS. GGS depends on 2D matches, which might be unreliable or unavailable in two-view settings. Therefore, I recommend evaluating PoseDiffusion's performance without GGS integration in your initial trials.

Best,
Jianyuan

**Comment by wuqun-tju** [comment]
> Hi,
> 
> Thanks for your interest. In our own preliminary experiments, PoseDiffusion can indeed deal with two-view relative camera pose estimation. However, the currently available checkpoint was trained for scenarios with 3 to N frames. To optimize performance for two-view scenarios, you may need to re-train with 2 to N frames. This is possibly important because, despite PoseDiffusion's ability to generalize across different frame counts, the jump from 3 to 2 frames involves specific challenges, which theoretically belongs to multi-view geometry or epipolar geometry.
> 
> Another important consideration is the role of GGS. GGS depends on 2D matches, which might be unreliable or unavailable in two-view settings. Therefore, I recommend evaluating PoseDiffusion's performance without GGS integration in your initial trials.
> 
> Best, Jianyuan

Hello， you mentioned "I recommend evaluating PoseDiffusion's performance without GGS integration in your initial trials".
In my opinion, poses are accurate with GGS.  What can be get if we just evaluate PoseDiffusion's performance without GGS.

**Comment by jytime** [comment]
Hi @wuqun-tju ,

It is just a step to debug. Basically we hope the model's output (Posediffusion without GGS) is reasonable so that the the result after GGS would be accurate. If the model's output is too noisy, GGS may break. Given the case mentioned above is a cross-dataset generalisation (from Co3D/Re10K to ScanNet), it would be beneficial to first check the model is good enough there. However, based on some feedback from different users, it seems our model is robust enough in different datasets like Scannet or Niantic.
