### ISSUE TITLE
Znear, and Zfar used in NDC

### ISSUE THREAD

**Issue by ZhenhuiL1n** [facebookresearch/PoseDiffusion#25]
Hi,

It is great work and I have a question:

What are the znear and zfar used in this work to define the NDC coordinate?

Thanks!

**Comment by jytime** [comment]
Hi,

Thank you! I humbly think this work does not require the setting of znear and zfar, because we do not involve operations related to the range of depth. For example, regarding GGS, we only need the xy value of 2D matches to compute the epipolar (sampson) distance. I think I just put znear and zfar as default or undefined. Please let me know if I misunderstand anything. 

Best,
Jianyuan
