### ISSUE TITLE
About focal length

### ISSUE THREAD

**Issue by YuyanHuang** [facebookresearch/PoseDiffusion#6]
Hi,
Does the model co3d_model_Apr16.pth released by you have requirements for the actual focal length of the test picture? Because I saw that the function pose_encoding_to_camera() in the script has two default values of minimum and maximum focus of 0.1 and 20. Also, is the focal length here in millimeters?

**Comment by YuyanHuang** [comment]
Because the focal length of the test data I collected through a professional camera is greater than 20 mm, or even 50 mm.

**Comment by jytime** [comment]
Hi @YuyanHuang ,

You are free to change the max and min value for focal length, because they were set to clamp extreme values during training and hence stabilize the training process. 

The predicted focal length was not in millimeters. They are normalised NDC focal length as explained in [pytorch3d](https://pytorch3d.org/docs/cameras).
